app = "tern"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 443
  protocol = "udp"

  [[services.ports]]
    port = 443

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
